language: csharp
dotnet: 3.1.404
solution: src/Reko-decompiler.sln
dist: xenial
os: linux

# This script builds the Mono version of Reko in the Un*x environment 
# of Travis-CI. When building the SLN file, we therefore use the "Release"
# target, which should be used when trying to build for .NET Framework 4.7.2.

# If you are building Reko for .NET Core on Un*x, you must use the UnixRelease
# target:
#   dotnet build -p:Configuration=UnixRelease
#
#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:ubuntu-toolchain-r/test'
#    packages:
#      - gcc-7
#      - g++-7

cache:
  directories:
    - $HOME/apt_cache

before_install:
  - source .travis_env
  - before_install

# If you want more build spew, change the /verbosity:minimal below
script:
  - source .travis_env
  - dotnet msbuild -p:Configuration=UnixRelease -p:Platform=x64 -v:m -t:build_solution -m ./src/BuildTargets/BuildTargets.csproj
  - dotnet msbuild -p:Configuration=Release -p:Platform=x64 -v:m -t:run_unit_tests -m ./src/BuildTargets/BuildTargets.csproj
  - dotnet msbuild -p:Configuration=Release -p:Platform=x64 -v:m -t:run_regressions -m ./src/BuildTargets/BuildTargets.csproj
