version: 0.9.2.{build}
clone_depth: 1

init: 
  - git config --global core.autocrlf false
 # The commented out line below displays RDP details for debugging on an AppVeyor VM
 # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# If you want more build spew, change the verbosity below
build:
  project: src/Reko-decompiler.sln
  verbosity: minimal

platform: x64
configuration: Release

environment:
  artifacts_dir: bin
  matrix:
    - job_name: ubuntu
      appveyor_build_worker_image: Ubuntu
      BUILD_CONFIGURATION: UnixRelease
    - job_name: macos
      appveyor_build_worker_image: macos
      BUILD_CONFIGURATION: UnixRelease
    - job_name: windows
      appveyor_build_worker_image: Visual Studio 2019
      BUILD_CONFIGURATION: Release

build_script:
  - ps: dotnet msbuild -p:Platform=$env:PLATFORM -p:Configuration=$env:BUILD_CONFIGURATION -v:m -t:build_solution -m ./src/BuildTargets/BuildTargets.csproj

after_build:
  - ps: dotnet msbuild -p:Platform=$env:PLATFORM -p:Configuration=$env:CONFIGURATION -v:m -t:create_runtime_nupkg -m ./src/BuildTargets/BuildTargets.csproj
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019"){ dotnet msbuild -p:Platform=$env:PLATFORM -p:Configuration=$env:CONFIGURATION -v:m -t:create_msi_wix -m ./src/BuildTargets/BuildTargets.csproj }
  - ps: dotnet msbuild -p:Platform=$env:PLATFORM -p:Configuration=$env:CONFIGURATION -v:m -t:create_release -m ./src/BuildTargets/BuildTargets.csproj

test_script:
  - ps: dotnet msbuild -p:Platform=$env:PLATFORM -p:Configuration=$env:CONFIGURATION -v:m -t:run_unit_tests -m ./src/BuildTargets/BuildTargets.csproj
  - ps: dotnet msbuild -p:Platform=$env:PLATFORM -p:Configuration=$env:CONFIGURATION -v:m -t:run_regressions -m ./src/BuildTargets/BuildTargets.csproj

for:
  -
    matrix:
      only:
        - job_name: ubuntu
    install:
      - sudo apt-get update -qq
      - sudo apt-get install -y libcapstone-dev pkg-config p7zip-full
  -
    matrix:
      only:
        - job_name: macos
    install:
      - brew install pkg-config capstone p7zip
  -
    matrix:
      only:
        - job_name: windows
  
artifacts:
  - path: bin/*.msi
    name: Reko installer
  - path: bin/WindowsDecompiler-*.zip
    name: Reko WinForms driver
  - path: bin/CmdLine-*.zip
    name: Reko CmdLine driver
  - path: bin/*.nupkg
    name: Reko Runtime (nuget package)

#on_finish:
# The commented out line below displays will keep the AppVeyor VM alive long enough for a RDP diagnostic
# session
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
