cmake_minimum_required ( VERSION 3.10 FATAL_ERROR )
list(INSERT CMAKE_MODULE_PATH 0 "${REKO_SRC}/../cmake")

include(msbuild2cmake)

message(STATUS "Building native libraries")
invoke_cmake(
	BUILD_DIR ${CMAKE_BINARY_DIR}/build/${REKO_PLATFORM}/${CMAKE_BUILD_TYPE}
	DIRECTORY ${CMAKE_SOURCE_DIR}
	VS_VERSION ${VS_VERSION}
	VS_MIN_VERSION ${VS_MIN_VERSION}
	PLATFORM ${REKO_ACTUAL_PLATFORM}
	PASS_VARIABLES
		CMAKE_BUILD_TYPE
)